[package]
name = "sapper_body_params"
version = "0.1.0"
authors = ["Mike Tang <miketang84@outlook.com>"]

[dependencies]
url = "1.0"
serde = "0.7"
serde_json = "0.7"
serde_macros = "0.7"

sapper = { git="https://github.com/sappworks/sapper" }
